### ISSUE TITLE
Don't find the file main.js in folder foxx/

### ISSUE THREAD

**Issue by franckzabi** [solisoft/foxx-framework#1]
I have followed your your tutorial but i don't obtained finally the same arborescence. Would you please give me some information about this issue. My folder foxx/ is empty.

Thanks.

**Comment by solisoft** [comment]
after a fresh install here my tree `$ foxxy new sample_app --database my_test_db`
then I did create symlinks as explained in output

````
cp -Rf /usr/local/var/lib/arangodb3-apps/_db/my_test_db/* /Users/soli/workspace/test/sample_app/sample_app/foxx
rm -Rf /usr/local/var/lib/arangodb3-apps/_db/my_test_db
ln -s /Users/soli/workspace/test/sample_app/sample_app/foxx /usr/local/var/lib/arangodb3-apps/_db/my_test_db
````

I think you ar missing this symlinks step

├── Gemfile
├── app
│   ├── assets
│   │   ├── fonts
│   │   ├── img
│   │   ├── index.html
│   │   └── login.html
│   ├── css
│   │   └── css.scss
│   ├── js
│   │   ├── common.js
│   │   └── js.js
│   ├── vendors
│   └── widgets
│       ├── loading.html.tag
│       └── login.html.tag
├── brunch-config.js
├── config
│   ├── deploy.rb
│   └── local_env.yml.sample
├── foxx
│   └── auth
│       └── APP
│           ├── README.md
│           ├── main.js
│           ├── manifest.json
│           ├── package.json
│           ├── scripts
│           │   ├── lost-password.js
│           │   ├── send-mail.js
│           │   └── setup.js
│           └── test
│               └── example.js
├── package.json
└── yarn.lock

**Comment by solisoft** [comment]
Just fixed documentation and added a gitter room ;) https://gitter.im/solisoft/foxxy
