### ISSUE TITLE
Model with collection relationship

### ISSUE THREAD

**Issue by rodmar35** [solisoft/foxx-framework#2]
Hi,

First, thanks for your framework ! I success to install and play with it
in documentation on your site, you explain creating a model with : 
`  
// { r: new_row, c: classname, n: name/id, t: type, j: joi validation, l: label, d: data list }
  
fields = [
{ r: true, c: "1-1", n: "title", t: "string", j: joi.string().required(), l: "Title" },
{ r: true, c: "1-2", n: "date", t: "date", j: joi.string().required(), l: "Publishing Date" },
{ r: false, c: "1-2", n: "draft", t: "list", j: joi.string().required(), l: "Draft?", d: [["y", "Yes"], ["n", "No"]] },
{ r: true, c: "1-1", n: "text", t: "text", j: joi.string().required(), l: "Text"}
]`

But could you give us an example for creating relationship with an another collection. By example adding a user_id in post collection.

Thanks in advance
Rodmar

**Comment by solisoft** [comment]
Hi @rodmar35, sorry for the delay I didn't see the notification.

To create a relation it's easy : 
```
var users = db._query("FOR user IN users RETURN [user._key, CONCAT( user.first_name, ' ', user.lastname)]")._documents
// Then on fields definition
fields = [
  { r: true,  c:"uk-width-1-1", n:"user_id", t:"list", j: joi.string().required(), l:"User", d: users },
  // Another fields definitions... 
]
```

That's it. Easy, isn't it ? Let me know your thoughts.
